# Generated by Django 5.0.3 on 2024-03-23 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_productrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cusotomer_addresses', to='main.customer'),
        ),
    ]
