# Generated by Django 5.0.3 on 2024-03-29 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_product_demo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='demo_url',
        ),
    ]
