# Generated by Django 5.0.3 on 2024-04-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_vendor_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='vendor_imgs/'),
        ),
    ]
