# Generated by Django 5.0.3 on 2024-04-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_vendor_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='cat_img',
            field=models.ImageField(null=True, upload_to='category_imgs/'),
        ),
    ]
